### ISSUE TITLE
Only one page opens when I select a chapter

### ISSUE THREAD

**Issue by kirreen** [kanishka-linux/ReadManga#2]
Hi!
So for some reason, only one page opens at a time now, i.e. scrolling doesn't work. I have to go to the Page tab and select every page specifially. It wasn't this way before.
How can I fix this? Do you need more info?

**Comment by kanishka-linux** [comment]
Please mention your GNU/Linux distro. Also mention whether you are using pyqt4 version or pyqt5 version, along with your installation method of this application.   
I haven't checked this application in a long time. Therefore it might be possible that something might have got broken in the application. Once you'll give the necessary info, I will try to fix it within few days.

**Comment by kirreen** [comment]
I'm on Arch, and it's the pyqt5 version. Thanks!

On 31 Jul 2017 9:11 PM, "AAK" <notifications@github.com> wrote:

Please mention your GNU/Linux distro. Also mention whether you are using
pyqt4 version or pyqt5 version, along with your installation method of this
application.
I haven't checked this application in a long time. Therefore it might be
possible that something might have got broken in the application. Once
you'll give the necessary info, I will try to fix it within few days.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/kanishka-linux/ReadManga/issues/2#issuecomment-319164021>,
or mute the thread

**Comment by kanishka-linux** [comment]
I just checked it, and scrolling is working fine here on both Arch and Ubuntu. As per design of the program, vertical scrollbar appears only when height of the image exceeds the height of the application window, and only after that scrolling down function works. In short if image is smaller than window then one may encounter the problem that you are facing. If such is the case, then try increasing size of the image using plus (+) key, till the scrollbar appears. Once scrollbar appears, the event for getting next page kicks in automatically. After that you can press 'o' key, to get images with original dimension, and then everything works normally. 

Edit: Vertical scrollbar is not visible in the application. It remains hidden, but it gets activated only when height of the image is greater than application window.

**Comment by kanishka-linux** [comment]
is the issue resolved?

**Comment by kirreen** [comment]
I guess, when the image is taller than the screen it does load the next image.
