### ISSUE TITLE
Keyboard navigation

### ISSUE THREAD

**Issue by Jzarecta** [kanishka-linux/ReadManga#4]
Hi anyway to add keyboard navigation like PgDown or Space to flip through the pages? also add some keystroke commands for moving through the chapters. That would be great. 
The QKeyEventClass could be helpful.
http://doc.qt.io/qt-5/qkeyevent.html 
Only key I was able to use is 'F' for full screen. But not even a Tooltip show on the 'Next' button.

**Comment by Jzarecta** [comment]
Oh found the documentation on it but for some reason "Down" nor Shift Left/Right work at least on fullscreen mode.

**Comment by kanishka-linux** [comment]
It is surprising that the application is still working. I haven't checked it for a long time. 
ctrl+right and ctrl+left can be used for flipping through the pages, and most of the shortcut keys work.
Most probably, you are using old version of qt. If you are using deb package which is based on qt4, then many features won't work.
